# Get memory fragmentation
UserParameter=os.mem_frag,awk '/MemTotal/{total=$2} /MemFree/{free=$2} /Buffers/{buf=$2} /^Cached/{cache=$2} END{printf "%.2f\n", (1-(free+buf+cache)/total)*100}' /proc/meminfo
